# Generated by Django 5.2.5 on 2025-08-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ingest/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='mode',
            field=models.CharField(choices=[('upload', 'upload'), ('s3', 's3'), ('gdrive', 'gdrive'), ('web', 'web'), ('email', 'email'), ('slack', 'slack'), ('github', 'github'), ('db', 'db'), ('api', 'api'), ('media', 'media')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('success', 'success'), ('failed', 'failed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestsource',
            name='kind',
            field=models.CharField(choices=[('local', 'Local'), ('s3', 'S3'), ('gdrive', 'GoogleDrive'), ('web', 'Web'), ('email', 'Email'), ('slack', 'Slack'), ('teams', 'Teams'), ('discord', 'Discord'), ('jira', 'Jira'), ('confluence', 'Confluence'), ('notion', 'Notion'), ('github', 'GitHub'), ('db', 'Database'), ('api', 'API'), ('media', 'Media')], max_length=20),
        ),
    ]
