# Generated by Django 5.2.5 on 2025-08-31 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_status_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingestfile',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='ingestjob',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='ingestsource',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='mode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ingest.ingestsource'),
        ),
        migrations.AlterField(
            model_name='ingestjob',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestsource',
            name='kind',
            field=models.CharField(max_length=20),
        ),
    ]
